# Generated by Django 2.2.13 on 2020-11-15 20:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='writeBlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('title', models.TextField()),
                ('blog', models.TextField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'blog',
            },
        ),
    ]
